/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/me": {
    /** Current user info */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MeResponse"];
          };
        };
      };
    };
  };
  "/api/v1/contacts": {
    /** List contacts */
    get: {
      parameters: {
        query?: {
          q?: string;
          tag?: string;
          has_email?: boolean;
          updated_since?: string;
          warmth_gte?: number;
          warmth_lte?: number;
          warmth_band?: "hot" | "warm" | "neutral" | "cool" | "cold";
          pipeline?: "networking" | "personal" | "business";
          stage?: string;
          sort?: "created_at.desc" | "created_at.asc" | "warmth.desc" | "warmth.asc";
          limit?: number;
          cursor?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ContactsListResponse"];
          };
        };
      };
    };
    /** Create contact */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ContactCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["ContactCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/contacts/{id}": {
    /** Get contact */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ContactResponse"];
          };
        };
      };
    };
    /** Delete contact */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["DeletedResponse"];
          };
        };
      };
    };
    /** Update contact */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ContactUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ContactResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/tags": {
    /** Modify tags */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TagsModifyRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ContactTagsUpdatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/notes": {
    /** List notes */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["NotesListResponse"];
          };
        };
      };
    };
    /** Create note */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["NoteCreateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["NoteCreatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/messages": {
    /** List messages for contact */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["TimelineListResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/files": {
    /** Link a file to contact */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["FileLinkRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AttachmentCreatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/warmth/recompute": {
    /** Recompute contact warmth */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["WarmthRecomputeResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/interactions": {
    /** List interactions */
    get: {
      parameters: {
        query?: {
          contact_id?: string;
          type?: string;
          start?: string;
          end?: string;
          limit?: number;
          cursor?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InteractionsListResponse"];
          };
        };
      };
    };
    /** Create interaction */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["InteractionCreateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InteractionCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/interactions/{id}": {
    /** Get interaction */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InteractionResponse"];
          };
        };
      };
    };
    /** Update interaction */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["InteractionUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["InteractionUpdatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/interactions/{id}/files": {
    /** Link a file to interaction */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["FileLinkRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AttachmentCreatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/messages": {
    /** Log a message */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MessageLogRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MessageCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/messages/{id}": {
    /** Get message */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MessageResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/messages/prepare": {
    /** Persist a drafted message */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MessagesPrepareRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["MessagesPrepareResponse"];
          };
        };
      };
    };
  };
  "/api/v1/messages/send": {
    /** Send a prepared message (provider stub) */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MessagesSendRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MessagesSendResponse"];
          };
        };
      };
    };
  };
  "/api/v1/files": {
    /** Request presigned upload */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UploadSignRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["UploadSignResponse"];
          };
        };
      };
    };
  };
  "/api/v1/compose": {
    /** Compose channel-specific draft */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ComposeRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ComposeResponse"];
          };
        };
      };
    };
  };
  "/api/v1/me/persona-notes": {
    /** List persona notes */
    get: {
      parameters: {
        query?: {
          type?: "text" | "voice";
          limit?: number;
          cursor?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PersonaNotesListResponse"];
          };
        };
      };
    };
    /** Create persona note */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PersonaNoteCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["PersonaNoteCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/me/persona-notes/{id}": {
    /** Get persona note */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PersonaNoteResponse"];
          };
        };
      };
    };
    /** Delete persona note */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["DeletedResponse"];
          };
        };
      };
    };
    /** Update persona note */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PersonaNoteUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PersonaNoteUpdatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/me/persona-notes/{id}/transcribe": {
    /** Transcribe voice note */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        /** @description Accepted */
        202: {
          content: never;
        };
      };
    };
  };
  "/api/v1/templates": {
    /** List templates */
    get: {
      parameters: {
        query?: {
          channel?: "email" | "sms" | "dm";
          limit?: number;
          cursor?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["TemplatesListResponse"];
          };
        };
      };
    };
    /** Create template */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TemplateCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["TemplateCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/templates/{id}": {
    /** Get template */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["TemplateResponse"];
          };
        };
      };
    };
    /** Delete template */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["DeletedResponse"];
          };
        };
      };
    };
    /** Update template */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TemplateUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["TemplateUpdatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/me/compose-settings": {
    /** Get compose settings */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ComposeSettingsResponse"];
          };
        };
      };
    };
    /** Update compose settings */
    patch: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ComposeSettingsUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ComposeSettingsResponse"];
          };
        };
      };
    };
  };
  "/api/v1/merge/contacts": {
    /** Merge contacts into a canonical record */
    post: {
    };
  };
  "/api/v1/audit-logs": {
    /** Admin: list audit logs */
    get: {
    };
  };
  "/api/v1/ops/health": {
    /** Admin: operational health */
    get: {
    };
  };
  "/api/v1/webhooks/test": {
    /** Admin: send a signed test webhook */
    post: {
    };
  };
  "/api/v1/me/account": {
    /** Enqueue account export+erase job */
    delete: {
    };
  };
  "/api/v1/.well-known/openapi.json": {
    /** OpenAPI 3.1 spec */
    get: {
    };
  };
  "/api/cron/interaction-metrics": {
    /** Cron: recompute interaction metrics */
    get: {
    };
  };
  "/api/telemetry/prompt-first": {
    /** Log first-prompt telemetry */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PromptFirstRequest"];
        };
      };
      responses: {
        /** @description created */
        201: {
          content: never;
        };
        /** @description ignored (privacy or empty) */
        204: {
          content: never;
        };
      };
    };
  };
  "/api/trending/prompts": {
    /** Get trending prompts */
    get: {
      parameters: {
        query?: {
          window?: "today" | "week" | "month";
          org?: "me" | "all";
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["TrendingPromptItem"][];
          };
        };
      };
    };
  };
  "/api/cron/prompts-rollup": {
    /** Cron: recompute trending prompts */
    get: {
    };
  };
  "/api/cron/paywall-rollup": {
    /** Cron: recompute paywall insights */
    get: {
    };
  };
  "/api/me/usage-summary": {
    /** Usage summary */
    get: {
      parameters: {
        query?: {
          window?: "30d" | "90d" | "mtd";
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["UsageSummaryResponse"];
          };
        };
      };
    };
  };
  "/api/me/impact-summary": {
    /** Impact summary */
    get: {
      parameters: {
        query?: {
          window?: "30d" | "90d" | "mtd";
          variant?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ImpactSummaryResponse"];
          };
        };
      };
    };
  };
  "/api/me/plan-recommendation": {
    /** Plan recommendation */
    get: {
      parameters: {
        query?: {
          variant?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PlanRecommendationResponse"];
          };
        };
      };
    };
  };
  "/api/v1/pipelines": {
    /** List pipelines */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PipelinesListResponse"];
          };
        };
      };
    };
  };
  "/api/v1/pipelines/{key}/stages": {
    /** List stages for a pipeline */
    get: {
      parameters: {
        path: {
          key: "networking" | "personal" | "business";
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PipelineStagesListResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        key: "networking" | "personal" | "business";
      };
    };
  };
  "/api/v1/contacts/{id}/pipeline": {
    /** Current pipeline state for contact */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PipelineStateResponse"];
          };
        };
      };
    };
    /** Set pipeline (initial stage) */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PipelineSetRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PipelineStateResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/pipeline/move": {
    /** Move to stage */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PipelineMoveRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PipelineMoveResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/pipeline/history": {
    /** Pipeline change history */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["PipelineHistoryListResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/goals": {
    /** List goals */
    get: {
      parameters: {
        query?: {
          kind?: "business" | "network" | "personal";
          scope?: "global" | "org" | "user";
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["GoalsListResponse"];
          };
        };
      };
    };
    /** Create custom goal */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GoalCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["GoalCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/goals/{id}": {
    /** Delete goal */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["DeletedResponse"];
          };
        };
      };
    };
    /** Update goal */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GoalUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["GoalUpdatedResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/goals/{id}/pin": {
    /** Pin/unpin a goal */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GoalPinRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["GoalPinResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/goal-suggestions": {
    /** Per-contact goal suggestions */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["GoalSuggestionsResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/compose/validate": {
    /** Validate compose variables against goal schema */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ComposeValidateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ComposeValidateResponse"];
          };
        };
      };
    };
  };
  "/api/v1/analysis/screenshot": {
    /** Create screenshot analysis */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ScreenshotAnalysisCreateRequest"];
        };
      };
      responses: {
        /** @description Accepted */
        201: {
          content: {
            "application/json": components["schemas"]["ScreenshotAnalysisCreatedResponse"];
          };
        };
      };
    };
  };
  "/api/v1/analysis/screenshot/{id}": {
    /** Get screenshot analysis */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ScreenshotAnalysisResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/contacts/{id}/context-summary": {
    /** Contact context summary */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ContactContextSummaryResponse"];
          };
        };
      };
    };
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/api/v1/telemetry/draft.accepted": {
    /** Telemetry: draft accepted */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ComposeDraftAcceptedRequest"];
        };
      };
      responses: {
        /** @description created */
        201: {
          content: never;
        };
      };
    };
  };
  "/api/v1/telemetry/draft.discarded": {
    /** Telemetry: draft discarded */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ComposeDraftDiscardedRequest"];
        };
      };
      responses: {
        /** @description created */
        201: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PromptFirstRequest: {
      prompt_raw: string;
      lang?: string;
      intent?: string;
      entities?: {
        [key: string]: unknown;
      };
      source?: string;
      session_id?: string;
      latency_ms?: number;
      result_kind?: string;
      error_code?: string;
      used?: boolean;
    };
    TrendingPromptItem: {
      rank?: number;
      representative_text?: string;
      intent?: string | null;
      uses?: number;
      impressions?: number;
      ctr?: number | null;
      score?: number | null;
      deep_link?: string;
    };
    UsageSummaryResponse: {
      window?: string;
      usage?: {
        contacts_created?: number;
        messages_drafted?: number;
        drafts_accepted?: number;
        messages_sent?: number;
        voice_minutes_used?: number;
        storage_used_mb?: number;
        compose_runs_used?: number;
        integrations_count?: number;
        top_intents?: {
            [key: string]: unknown;
          }[];
        updated_at?: string | null;
      };
      limits?: {
        compose_runs?: number;
        voice_minutes?: number;
        messages?: number;
      };
      assumptions?: string[];
    };
    ImpactSummaryResponse: {
      window?: string;
      variant?: string;
      impact?: {
        reply_rate?: number | null;
        time_saved_minutes?: number | null;
        warmth_avg_delta?: number | null;
        reengaged_contacts?: number;
        updated_at?: string | null;
        explainers?: string[];
      };
    };
    PlanRecommendationResponse: {
      variant?: string;
      /** @enum {string} */
      suggested_plan?: "starter" | "pro";
      rationale?: string[];
      projected_overage?: {
        compose_runs?: number;
        voice_minutes?: number;
        messages?: number;
      };
    };
    Contact: {
      /** Format: uuid */
      id?: string;
      display_name?: string;
      emails?: string[];
      phones?: string[];
      company?: string | null;
      notes?: string | null;
      tags?: string[];
      /** Format: uri */
      avatar_url?: string | null;
      metadata?: {
        [key: string]: unknown;
      } | null;
      warmth?: number | null;
      warmth_band?: string | null;
      warmth_override?: boolean | null;
      warmth_override_reason?: string | null;
      /** Format: date-time */
      last_interaction_at?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    ContactCreateRequest: {
      display_name: string;
      emails?: string[];
      phones?: string[];
      company?: string;
      notes?: string;
      tags?: string[];
      /** Format: uri */
      avatar_url?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    ContactUpdateRequest: {
      display_name?: string;
      emails?: string[];
      phones?: string[];
      company?: string;
      notes?: string;
      tags?: string[];
      /** Format: uri */
      avatar_url?: string;
      metadata?: {
        [key: string]: unknown;
      };
      warmth?: number;
      warmth_override?: boolean;
      warmth_override_reason?: string;
    };
    ContactsListResponse: {
      items?: components["schemas"]["Contact"][];
      limit?: number;
      nextCursor?: string | null;
    };
    ContactResponse: {
      contact?: components["schemas"]["Contact"];
    };
    ContactCreatedResponse: {
      contact?: {
        id?: string;
        display_name?: string;
        created_at?: string;
      };
    };
    InteractionCreateRequest: {
      /** Format: uuid */
      contact_id: string;
      kind?: string;
      content?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    InteractionCreatedResponse: {
      interaction?: {
        id?: string;
        contact_id?: string;
        kind?: string;
        created_at?: string;
      };
    };
    InteractionsListResponse: {
      items?: components["schemas"]["Interaction"][];
      limit?: number;
      nextCursor?: string | null;
    };
    MessageLogRequest: {
      content: string;
      /** @enum {string} */
      role?: "user" | "assistant" | "system" | "note";
      /** Format: uuid */
      thread_id?: string;
      /** Format: uuid */
      contact_id?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    MessageCreatedResponse: {
      message?: {
        id?: string;
        thread_id?: string;
        role?: string;
        content?: string;
        metadata?: {
          [key: string]: unknown;
        };
        created_at?: string;
      };
    };
    MessagesPrepareRequest: {
      /** Format: uuid */
      contact_id?: string;
      /** Format: uuid */
      thread_id?: string;
      /** @enum {string} */
      channel: "email" | "sms" | "dm";
      draft: {
        subject?: string;
        body: string;
        closing?: string;
      };
      composer_context?: {
        [key: string]: unknown;
      };
    };
    MessagesPrepareResponse: {
      message?: {
        id?: string;
        thread_id?: string;
        created_at?: string;
      };
      compose_session_id?: string | null;
    };
    MessagesSendRequest: {
      /** Format: uuid */
      message_id: string;
      channel_account_id?: string;
    };
    MessagesSendResponse: {
      sent?: boolean;
      message_id?: string;
      sent_at?: string;
      delivery_status?: string;
    };
    ComposeRequest: {
      /** Format: uuid */
      contact_id: string;
      /** @enum {string} */
      channel: "email" | "sms" | "dm";
      goal: string;
      /** Format: uuid */
      template_id?: string;
      variables?: {
        [key: string]: unknown;
      };
      include?: {
        persona_notes?: boolean;
        recent_interactions?: number;
        screenshots?: boolean;
        voice_tone?: boolean;
      };
    };
    ComposeResponse: {
      compose_session_id?: string | null;
      draft?: {
        email?: {
          subject?: string;
          body?: string;
          closing?: string;
        } | null;
        sms?: {
          body?: string;
        } | null;
        dm?: {
          body?: string;
        } | null;
      };
      sources?: {
        persona_note_ids?: string[];
        contact_context?: {
          [key: string]: unknown;
        } | null;
        template_id?: string | null;
      };
      alternatives?: Record<string, never>[];
      safety?: {
        pii_flags?: string[];
        spam_risk?: string;
      };
    };
    PersonaNote: {
      id?: string;
      /** @enum {string} */
      type?: "text" | "voice";
      title?: string | null;
      body_text?: string | null;
      file_url?: string | null;
      duration_sec?: number | null;
      transcript?: string | null;
      tags?: string[];
      created_at?: string;
      updated_at?: string;
    };
    PersonaNotesListResponse: {
      items?: components["schemas"]["PersonaNote"][];
      limit?: number;
      nextCursor?: string | null;
    };
    PersonaNoteCreateRequest: {
      /** @enum {string} */
      type: "text" | "voice";
      title?: string;
      body_text?: string;
      file_url?: string;
      duration_sec?: number;
      tags?: string[];
    };
    PersonaNoteCreatedResponse: {
      note?: {
        id?: string;
        type?: string;
        title?: string;
        created_at?: string;
      };
    };
    PersonaNoteResponse: {
      note?: components["schemas"]["PersonaNote"];
    };
    PersonaNoteUpdateRequest: {
      title?: string;
      body_text?: string;
      file_url?: string;
      duration_sec?: number;
      transcript?: string;
      tags?: string[];
    };
    PersonaNoteUpdatedResponse: {
      note?: {
        id?: string;
        updated_at?: string;
      };
    };
    Template: {
      id?: string;
      /** @enum {string} */
      channel?: "email" | "sms" | "dm";
      name?: string;
      description?: string | null;
      subject_tmpl?: string | null;
      body_tmpl?: string;
      closing_tmpl?: string | null;
      variables?: Record<string, never>[];
      /** @enum {string} */
      visibility?: "private" | "team" | "org";
      is_default?: boolean;
      created_at?: string;
      updated_at?: string;
    };
    TemplatesListResponse: {
      items?: components["schemas"]["Template"][];
      limit?: number;
      nextCursor?: string | null;
    };
    TemplateCreateRequest: {
      /** @enum {string} */
      channel: "email" | "sms" | "dm";
      name: string;
      description?: string;
      subject_tmpl?: string;
      body_tmpl: string;
      closing_tmpl?: string;
      variables?: Record<string, never>[];
      /** @enum {string} */
      visibility?: "private" | "team" | "org";
    };
    TemplateCreatedResponse: {
      template?: {
        id?: string;
        channel?: string;
        name?: string;
        created_at?: string;
      };
    };
    TemplateResponse: {
      template?: components["schemas"]["Template"];
    };
    TemplateUpdateRequest: {
      /** @enum {string} */
      channel?: "email" | "sms" | "dm";
      name?: string;
      description?: string;
      subject_tmpl?: string;
      body_tmpl?: string;
      closing_tmpl?: string;
      variables?: Record<string, never>[];
      /** @enum {string} */
      visibility?: "private" | "team" | "org";
      is_default?: boolean;
    };
    TemplateUpdatedResponse: {
      template?: {
        id?: string;
        updated_at?: string;
      };
    };
    ComposeSettings: {
      user_id?: string;
      enabled?: boolean;
      /** @enum {string} */
      default_channel?: "email" | "sms" | "dm";
      auto_use_persona_notes?: boolean;
      default_template_id?: string | null;
      /** @enum {string} */
      tone?: "concise" | "warm" | "professional" | "playful";
      max_length?: number | null;
      guardrails?: {
        [key: string]: unknown;
      };
      updated_at?: string | null;
    };
    ComposeSettingsUpdateRequest: {
      enabled?: boolean;
      /** @enum {string} */
      default_channel?: "email" | "sms" | "dm";
      auto_use_persona_notes?: boolean;
      /** Format: uuid */
      default_template_id?: string | null;
      /** @enum {string} */
      tone?: "concise" | "warm" | "professional" | "playful";
      max_length?: number | null;
      guardrails?: {
        [key: string]: unknown;
      };
    };
    ComposeSettingsResponse: {
      settings?: components["schemas"]["ComposeSettings"];
    };
    DeletedResponse: {
      deleted?: boolean;
      id?: string | null;
      contact?: {
        [key: string]: unknown;
      } | null;
    };
    TagsModifyRequest: {
      add?: string[];
      remove?: string[];
    };
    ContactTagsUpdatedResponse: {
      contact?: {
        id?: string;
        tags?: string[];
        updated_at?: string;
      };
    };
    Interaction: {
      id?: string;
      contact_id?: string;
      kind?: string;
      content?: string | null;
      metadata?: {
        [key: string]: unknown;
      };
      created_at?: string;
      updated_at?: string;
    };
    NotesListResponse: {
      items?: components["schemas"]["Interaction"][];
      limit?: number;
      nextCursor?: string | null;
    };
    NoteCreateRequest: {
      content?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    NoteCreatedResponse: {
      note?: {
        id?: string;
        contact_id?: string;
        kind?: string;
        created_at?: string;
      };
    };
    TimelineItem: {
      /** @enum {string} */
      type?: "interaction" | "message";
      id?: string;
      created_at?: string;
      payload?: {
        [key: string]: unknown;
      };
    };
    TimelineListResponse: {
      items?: components["schemas"]["TimelineItem"][];
      limit?: number;
      nextCursor?: string | null;
    };
    FileLinkRequest: {
      path: string;
      mime_type?: string;
      size_bytes?: number;
    };
    AttachmentCreatedResponse: {
      attachment?: {
        id?: string;
        file_path?: string;
        created_at?: string;
      };
    };
    WarmthRecomputeResponse: {
      contact?: {
        id?: string;
        warmth?: number;
        warmth_band?: string;
        warmth_updated_at?: string;
      };
    };
    InteractionResponse: {
      interaction?: components["schemas"]["Interaction"];
    };
    InteractionUpdateRequest: {
      content?: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    InteractionUpdatedResponse: {
      interaction?: {
        id?: string;
        updated_at?: string;
      };
    };
    UploadSignRequest: {
      path: string;
      contentType?: string;
    };
    UploadSignResponse: {
      url?: string;
      path?: string;
      contentType?: string;
    };
    MessageResponse: {
      message?: {
        id?: string;
        thread_id?: string;
        role?: string;
        content?: string;
        metadata?: {
          [key: string]: unknown;
        };
        created_at?: string;
        updated_at?: string;
      };
    };
    MeResponse: {
      user?: {
        id?: string;
        email?: string | null;
        display_name?: string | null;
      };
      org?: null;
      billing?: ({
        stripe_customer_id?: string | null;
        stripe_subscription_id?: string | null;
        stripe_price_id?: string | null;
        subscription_status?: string | null;
        current_period_end?: string | null;
      }) | null;
    };
    Pipeline: {
      id?: string;
      /** @enum {string} */
      key?: "networking" | "personal" | "business";
      name?: string;
      created_at?: string;
    };
    PipelinesListResponse: {
      items?: components["schemas"]["Pipeline"][];
    };
    PipelineStage: {
      id?: string;
      pipeline_id?: string;
      key?: string;
      name?: string;
      position?: number;
      terminal?: boolean;
    };
    PipelineStagesListResponse: {
      items?: components["schemas"]["PipelineStage"][];
    };
    PipelineStateResponse: {
      contact_id?: string;
      pipeline_id?: string;
      stage_id?: string;
      pipeline_key?: string;
      stage_key?: string;
      stage_name?: string;
      started_at?: string;
      updated_at?: string;
      allowed_moves?: {
          stage_id?: string;
          stage_key?: string;
          stage_name?: string;
        }[];
    };
    PipelineSetRequest: {
      /** @enum {string} */
      pipeline_key: "networking" | "personal" | "business";
      stage_key?: string;
    };
    PipelineMoveRequest: {
      /** Format: uuid */
      stage_id: string;
      reason?: string;
    };
    PipelineMoveResponse: {
      from_stage_id?: string | null;
      to_stage_id?: string;
      changed_by_user_id?: string;
      reason?: string | null;
      created_at?: string;
    };
    PipelineHistoryItem: {
      id?: string;
      contact_id?: string;
      pipeline_id?: string;
      from_stage_id?: string | null;
      to_stage_id?: string;
      changed_by_user_id?: string;
      reason?: string | null;
      created_at?: string;
    };
    PipelineHistoryListResponse: {
      items?: components["schemas"]["PipelineHistoryItem"][];
      limit?: number;
      nextCursor?: string | null;
    };
    Goal: {
      id?: string;
      org_id?: string | null;
      owner_user_id?: string | null;
      /** @enum {string} */
      kind?: "business" | "network" | "personal";
      name?: string;
      description?: string | null;
      channel_suggestions?: string[];
      variables_schema?: {
        [key: string]: unknown;
      };
      default_template_id?: string | null;
      is_active?: boolean;
      popularity_score?: number;
      created_at?: string;
      updated_at?: string;
    };
    GoalsListResponse: {
      items?: components["schemas"]["Goal"][];
    };
    GoalCreateRequest: {
      /** @enum {string} */
      kind: "business" | "network" | "personal";
      name: string;
      description?: string;
      channel_suggestions?: string[];
      variables_schema?: {
        [key: string]: unknown;
      };
      default_template_id?: string;
    };
    GoalCreatedResponse: {
      goal?: {
        id?: string;
        name?: string;
        created_at?: string;
      };
    };
    GoalUpdateRequest: {
      /** @enum {string} */
      kind?: "business" | "network" | "personal";
      name?: string;
      description?: string;
      channel_suggestions?: string[];
      variables_schema?: {
        [key: string]: unknown;
      };
      default_template_id?: string;
      is_active?: boolean;
    };
    GoalUpdatedResponse: {
      goal?: {
        id?: string;
        updated_at?: string;
      };
    };
    GoalPinRequest: {
      pinned?: boolean;
    };
    GoalPinResponse: {
      goal_id?: string;
      pinned?: boolean;
    };
    GoalSuggestionsResponse: {
      items?: ({
          goal_id?: string;
          name?: string;
          score?: number;
          reason?: string | null;
        })[];
    };
    ComposeValidateRequest: {
      /** Format: uuid */
      goal_id?: string;
      goal_text?: string;
      variables?: {
        [key: string]: unknown;
      };
    };
    ComposeValidateResponse: {
      ok?: boolean;
      missing?: string[];
      errors?: string[];
    };
    ScreenshotAnalysisCreateRequest: {
      file_url: string;
      /** Format: uuid */
      contact_id?: string;
    };
    ScreenshotAnalysisCreatedResponse: {
      analysis_id?: string;
      /** @enum {string} */
      status?: "pending" | "processing" | "ready" | "failed";
    };
    ScreenshotAnalysisResponse: {
      analysis_id?: string;
      /** @enum {string} */
      status?: "pending" | "processing" | "ready" | "failed";
      ocr_text?: string | null;
      inferred_goal?: ({
        id?: string | null;
        text?: string | null;
      }) | null;
      variables?: {
        [key: string]: unknown;
      };
      confidence?: number | null;
      created_at?: string;
      updated_at?: string;
    };
    ContactContextSummaryResponse: {
      last_contact_delta_days?: number | null;
      last_topics?: string[];
      interests?: string[];
      warmth?: number | null;
      warmth_band?: string | null;
      recent_interactions?: {
          id?: string;
          type?: string;
          created_at?: string;
          snippet?: string;
        }[];
    };
    ComposeDraftAcceptedRequest: {
      /** Format: uuid */
      compose_session_id: string;
    };
    ComposeDraftDiscardedRequest: {
      /** Format: uuid */
      compose_session_id: string;
      reason?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
