import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  TouchableOpacity,
  Linking,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { ArrowLeft } from 'lucide-react-native';
import { Stack } from 'expo-router';
import { useAnalytics } from '@/hooks/useAnalytics';

export default function PrivacyPolicyScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();

  // Analytics tracking
  useAnalytics('PrivacyPolicy');
  const lastUpdated = 'Oct 30, 2025';

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <Stack.Screen 
        options={{
          title: 'Privacy Policy',
          headerShown: true,
          headerLeft: () => (
            <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
              <ArrowLeft size={24} color="#000000" />
            </TouchableOpacity>
          ),
        }} 
      />
      
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        <View style={styles.content}>
          <Text style={styles.title}>Privacy Policy</Text>
          <Text style={styles.lastUpdated}>Last updated: {lastUpdated}</Text>
          <TouchableOpacity 
            onPress={() => Linking.openURL('https://www.everreach.app/privacy-policy')}
            style={styles.webLinkContainer}
          >
            <Text style={styles.webLink}>https://www.everreach.app/privacy-policy</Text>
          </TouchableOpacity>
          
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>1. Information We Collect</Text>
            <Text style={styles.paragraph}>
              We collect information you provide directly to us (e.g., when creating an account, importing
              contacts, recording voice notes) and technical data generated by your use of EverReach. This may include:
            </Text>
            <Text style={styles.bulletPoint}>• Contact information (names, emails, phone numbers)</Text>
            <Text style={styles.bulletPoint}>• Voice recordings and transcripts (when you explicitly record)</Text>
            <Text style={styles.bulletPoint}>• Notes and interaction history</Text>
            <Text style={styles.bulletPoint}>• Subscription status and purchase receipts</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>2. How We Use Your Information</Text>
            <Text style={styles.paragraph}>We use the information we collect to:</Text>
            <Text style={styles.bulletPoint}>• Provide and maintain our CRM services</Text>
            <Text style={styles.bulletPoint}>• Sync your data across devices (when enabled)</Text>
            <Text style={styles.bulletPoint}>• Generate AI‑powered insights and suggestions</Text>
            <Text style={styles.bulletPoint}>• Process payments and manage subscriptions</Text>
            <Text style={styles.bulletPoint}>• Communicate with you about our services</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>3. Data Storage and Security</Text>
            <Text style={styles.paragraph}>Your data is stored locally on your device by default. When you enable cloud sync:</Text>
            <Text style={styles.bulletPoint}>• Data is encrypted in transit and at rest</Text>
            <Text style={styles.bulletPoint}>• We use industry-standard security measures</Text>
            <Text style={styles.bulletPoint}>• You can disable cloud sync at any time</Text>
            <Text style={styles.bulletPoint}>• Local data remains on your device even when syncing is disabled</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>4. Data Sharing</Text>
            <Text style={styles.paragraph}>
              We do not sell personal data and we do not share data with advertising networks or use advertising SDKs.
              We share data with service providers only as needed to operate EverReach:
            </Text>
            <Text style={styles.bulletPoint}>• With your explicit consent</Text>
            <Text style={styles.bulletPoint}>• To comply with legal obligations</Text>
            <Text style={styles.bulletPoint}>• To protect our rights and safety</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>5. Your Rights</Text>
            <Text style={styles.paragraph}>
              You have the right to:
            </Text>
            <Text style={styles.bulletPoint}>• Access your personal data</Text>
            <Text style={styles.bulletPoint}>• Correct inaccurate data</Text>
            <Text style={styles.bulletPoint}>• Delete your data</Text>
            <Text style={styles.bulletPoint}>• Export your data</Text>
            <Text style={styles.bulletPoint}>• Disable cloud sync and keep data local</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>6. Contact Us</Text>
            <Text style={styles.paragraph}>
              If you have any questions about this Privacy Policy, please contact us at:
            </Text>
            <Text style={styles.contactInfo}>privacy@everreach.app</Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  backButton: {
    padding: 8,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  lastUpdated: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 32,
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333333',
    marginBottom: 12,
  },
  bulletPoint: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333333',
    marginBottom: 8,
    marginLeft: 16,
  },
  contactInfo: {
    fontSize: 16,
    lineHeight: 24,
    color: '#007AFF',
    fontWeight: '500',
  },
  webLinkContainer: {
    marginBottom: 24,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#EEF2FF',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  webLink: {
    color: '#4F46E5',
    fontSize: 14,
    fontWeight: '600',
  },
});